### ISSUE TITLE
[Suggestion]: add a limit to amount of messages per job 

### ISSUE THREAD

**Issue by karidra** [CircleCI-Public/slack-orb#156]
Hi all,
As of now, there is no parameter to limit the amount of messages sent by the Slack Orb. This is a bit of an inconvenience for large runs with several jobs and nodes, as there are several slack notifications for the same problem. Would it be possible to add a parameter to limit the amount of messages sent per run?

**Comment by KyleTryon** [comment]
@karidra The slack orb (and all orbs) works by running some bash as a step within a job. This limits the scope of what the orb is able to do as it only has the context of the job it is active in, there is no logic running at a higher level to capture the output from multiple jobs at the same time.

Because of this, if you send a notification in a job with 3x parallelism, you would receive all three notifications.

We considered maybe only showing notifications from node 0 (the first of any parallel job), but this isn't very helpful as it's possible for one parallel job to pass and another to fail, but you would only receive the alert to the first node.

We are making progress towards internal webhooks which will eventually be able to be processed and give the functionality you are requesting.

**Comment by karidra** [comment]
@KyleTryon That's great, thankyou!
