### ISSUE TITLE
Update `successful_tagged_deployment.yml` example

### ISSUE THREAD

**Issue by apple12347678** [CircleCI-Public/slack-orb#316]
## Describe Request:

https://github.com/CircleCI-Public/slack-orb/blob/master/src/examples/successful_tagged_deployment.yml

This code example yaml configuration file is explaining about `basic_fail_1` template, not `success_tagged_deploy_1`. As the [official documentation](https://circleci.com/developer/orbs/orb/circleci/slack#usage-successful_tagged_deployment) also seems to reference this code, I had to dig into the source code to find out how to use this template.

If I'm able to setup a job with this template, I would mind contributing to this example.

**Comment by EricRibeiro** [comment]
Nice catch, @apple12347678! 

I'll push the fix shortly!

> If I'm able to setup a job with this template, I would mind contributing to this example.

That's awesome because we do encourage community contributions. For future reference, you can make the change, open a PR, and I can trigger the jobs on my end. Alternatively, you can fork the repo and set up a pipeline with your own changed orb to run the integration or your tests.
