### ISSUE TITLE
Interactively approve the workflow

### ISSUE THREAD

**Issue by vallard** [CircleCI-Public/slack-orb#331]
## Describe Request:
Hi, I have my workflows on pause and slack notifies me nicely of this.  I found the instructions very clear, thank you for that!
Is there a way I can just approve this through slack rather than having to click the link, open up circleci and approve?  Do I need to build a server bot for that? It may be a bit out of scope for this orb but was just wondering as I think it would be super handy.  

Thanks!

**Comment by EricRibeiro** [comment]
Hi @vallard 👋 

> Do I need to build a server bot for that?

This is probably the best approach for what you are trying to accomplish. If you are using the built-in `basic_on_hold` template, my suggestion is to create a [custom](1c197b9f-f2fc-4882-a142-be5ac2d3fcf0) or [dynamic](https://github.com/CircleCI-Public/slack-orb/wiki/Dynamic-Templates) template with its content plus the workflow and job IDs. Both are available as the build environment variables `CIRCLE_WORKFLOW_ID` and `CIRCLE_WORKFLOW_JOB_ID` respectively.

You need these two values as arguments for the [CircleCI API](https://circleci.com/docs/api/v2/), specifically the [approve endpoint](https://circleci.com/docs/api/v2/#operation/approvePendingApprovalJobById). And having them readily available in the notification will spare you clicking on the workflow link and manually getting the IDs (which defeats the purpose of what you are trying to do).

Then you need a slack bot capable of making REST requests to the CircleCI API on your behalf. This way, after receiving a slack notification: 

**ON HOLD - Awaiting Approval** :raised_hand:
**Project:** slack-orb     **Branch:** main
**Author:** Eric
**Mentions:** @EricRibeiro 
**Job ID:** a176443d-f30d-421c-bc3b-c04634c6d44c
**Workflow ID:** 1c197b9f-f2fc-4882-a142-be5ac2d3fcf0

You can do a command like:

```
/circleci approve job_id workflow_id
```

Where `/circleci` is the command that triggers your bot, `approve` is the keyword that associates the command to the [approve endpoint](https://circleci.com/docs/api/v2/#operation/approvePendingApprovalJobById) and `job_id` and `workflow_id` are the values you got from the slack orb notification.

Please keep in mind this is just a suggestion. 

I'll close this issue since it's unrelated to the slack-orb, but I would love it if you post your updates here and let me know how it worked out for you.
