### ISSUE TITLE
Slack Orb is broken

### ISSUE THREAD

**Issue by apujari-hippo** [CircleCI-Public/slack-orb#403]
## What happened:

Slack Orb is broken after today's changes (04/26/2023)
https://github.com/CircleCI-Public/slack-orb/commit/b1d05c0b72b23efb7b42d157fd511b453fd874af

## Additional Information:

ERROR:
```
Posting Status
BASH_ENV file: /tmp/.bash_env-64498232fc0bd3432523f9b7-0-build
Does Not Exist. Skipping file execution
Checking For JQ + CURL
environment: line 213: circleci: command not found

Exited with code exit status 127
CircleCI received exit code 127
```

**Comment by EricRibeiro** [comment]
Hi @apujari-hippo and @wyardley 👋 

Thank you for bringing this to our attention. Could you share the following information:

- Are you using a self-hosted runner?
- If "no" to the above, are you using CircleCI server? Which version?
- If "no" to both questions above, what image are you using to run the job?

If you run a public pipeline, could you share the link? If it's private, please contact [our support](https://support.circleci.com/hc/en-us/requests/new) to provide us with more information so we can better assist you.

**Comment by EricRibeiro** [comment]
Thank you both for the heads-up and your patience 🙇 

We are investigating why self-hosted runners didn't receive the update. This also brought to our attention that we should include runners in our test suite to catch these cases (cc @KyleTryon).

v4.12.3 will be out shortly.

**Comment by wyardley** [comment]
FWIW, we build a custom Docker image, however, we build it at least somewhat frequently. That said, there could be some lag.

Wouldn't other non-circle base images [running on the platform] _also_ not have the circleci CLI present potentially, or does it get installed automagically there?

**Comment by EricRibeiro** [comment]
> Wouldn't other non-circle base images [running on the platform] also not have the circleci CLI present potentially, or does it get installed automagically there?

It does. The problem lies in how the magic happens with Runner specifically. Our initial investigation showed that the CLI is not aliased to "circleci" when using self-hosted runners, hence the `circleci: command not found` error. In contrast, [all tests](https://app.circleci.com/pipelines/github/CircleCI-Public/slack-orb/1681/workflows/7ad39d21-98c4-47ff-be60-2bd017646b25/jobs/9860) using cloud executors pass.

We raise the issue internally. In the meantime, we will refrain from using `circleci env subst` in our orbs.
