### ISSUE TITLE
Documentation/examples in readme use old version of orb

### ISSUE THREAD

**Issue by CharlieEriksen** [CircleCI-Public/slack-orb#42]
### Orb version
1.0.0

### What happened

The documentation in this repo's readme do not work, because they use the 1.0.0 orb. For instance, success_message in the status call does not work with the 1.0.0 orb. 

### Expected behavior

The examples should use the latest orb, such that they provided examples in the readme actually work.

**Comment by KyleTryon** [comment]
The solution to this would be to either manually update all documentation with every push or change the documentation example to use `@volatile`.  We may not want to promote the use of `@volatile` due to the fact users may grab that from the example in the same way you have grabbed 1.0.0 and run into similar issues when things change.

Would a comment next to the version mentioning you should specifically set your version work @CharlieEriksen ?

@iynere any thoughts?

**Comment by iynere** [comment]
@CharlieEriksen the version used in examples / readmes are not meant to conform to the latest version of the orb, it's just an example

@KyleTryon people report this issue all the time on our other orbs, so what i've started doing is changing the versions to x.y.z in the readmes, to make it obvious that it's just intended to show how to use SemVer with orbs.... but that doesn't address the versions in the actual orb.

it would probably be fairly straightforward to make an `orb-tools` job that we can run automatically after any orb has a prod version published, that would update the version numbers in all that orb's examples, & then publish a new patch release, what do you think ?
