### ISSUE TITLE
enable setting channel option

### ISSUE THREAD

**Issue by sibelius** [CircleCI-Public/slack-orb#53]
### Orb version

2.5.0

### What happened
I can't specify the channel

### Expected behavior

It should be able to specify the channel

### How I do today:

```jsx
slack chat send "ok"  --channel '#mychannel'
```

**Comment by iynere** [comment]
sorry, specify the channel for what ? @sibelius 

all of the orb's functionality supports channel-specific messaging / notifications—it's configured when you create your webhook:

https://github.com/CircleCI-Public/slack-orb#how-to-get-your-slack-webhook

**Comment by sibelius** [comment]
I want to use the same webhook, but publish to different channels

**Comment by iynere** [comment]
i dont' think that's possible, AFAIK, because the webhook is created on a per-channel basis @sibelius 

@KyleTryon do you know ?

**Comment by sibelius** [comment]
this works on https://github.com/rockymadden/slack-cli

**Comment by danpalmer** [comment]
I think the issue here is that the Slack CLI client mentioned by @sibelius uses a Slack API token, whereas this Slack Orb uses a webhook URL, which is tied to a specific channel.

It would be nice to move to using an API token perhaps, to allow more customisation. I'm looking to re-implement our Slack notifications in CircleCI config, we currently have the behaviour that release notifications go to `#general` while more detailed notifications go to `#tech`.

**Comment by KyleTryon** [comment]
Hello,

@danpalmer  is correct. The Slack SLI is not utilized by this Slack Orb. We originally chose the WebHook method for compatibility and lower dependencies. 

The WebHook value is stored as an environment variable or as a parameter to the Orb and so can be changed via the config by offering an alternative webhook if you want Job X to post to channel X and Job Y to channel Y.

Another option of course is for us to consider using the Slack CLI rather than webhooks. I think this is a much larger discussion as it means installing a CLI client in a user's job in order to communicate with SLACK rather than simply using CURL which is likely on the machine.

I would most likely vote that Webhooks are the best solution, given the webhook parameter can be changed to include multiple channels but I do see what ya'll mean and you may want to define multiple notifications per job.

Id love to get more feedback on this.

**Comment by Supernats** [comment]
@KyleTryon I agree that webhooks are the easiest way to get this going. All the situations I've seen detailed here seem like they could be implemented with the existing webhook offering.

In terms of possible expansions, I can think of two that would lead to greater quality of life when using this.
1. A channel-to-webhook dictionary, so that the destinations are easier for people to keep track of.
1. The ability to use multiple webhooks for a specific action, to push the same message to multiple channels at the same time without copying the action.

**Comment by iynere** [comment]
@Supernats what @KyleTryon is describing is essentially already a channel-to-webhook dictionary:

> The WebHook value is stored as an environment variable or as a parameter to the Orb and so can be changed via the config by offering an alternative webhook if you want Job X to post to channel X and Job Y to channel Y.

If you store your channel webhooks as different env vars (e.g., `SLACK_WEBHOOK_ENG_CHANNEL`, `SLACK_WEBHOOK_RELEASE_CHANNEL`), then you can reference those webhooks easily in your config.yml

**Comment by Supernats** [comment]
@iynere you're absolutely right. I didn't think about using Bash vars to handle this. Thanks!

**Comment by iynere** [comment]
@Supernats sorry, not bash vars, altho i suppose that would work—i'd recommend storing that information as CircleCI project environment variables—or even better, in a Context, since probably multiple projects within your org will make use of the Slack orb

**Comment by Supernats** [comment]
@iynere You're blowing my mind over here! I did not know about Contexts, and they are absolutely what I've been missing. Thanks so much.

**Comment by rail44** [comment]
> i dont' think that's possible, AFAIK, because the webhook is created on a per-channel basis @sibelius

it's possible by `channel` field within POST json.
see `simplest exmaple` section of this document https://api.slack.com/docs/message-attachments

**Comment by wyardley** [comment]
We have multi-channel webhooks, and this would be a very useful feature for us, FWIW.
We do something similar with an internal tool we use for sending slack notifications.
