### ISSUE TITLE
[Question] is it possible to consolidate and send 1 slack message when the job runs in parallel?

### ISSUE THREAD

**Issue by noralin** [CircleCI-Public/slack-orb#73]
I tried to configure slack/status for a job that has parallelism on, we're using 5 containers, so we get 5 separate slack notifications, one from each container. 

Is it possible for it to wait for all containers to be done, and send 1 slack message at the end and for it to show "failed" if any of the containers failed, and show "success" if all were successful?

**Comment by KyleTryon** [comment]
Hello @noralin,

The status in that situation would have to be reported by a job fired after the job with parallelism. At the moment I do not believe this is possible. It may be possible with some advanced usage of the API.  I will leave this open for now while we investigate that possibility.

**Comment by timothyclarke** [comment]
How about using a workflow to perform the success notification in a later job and a `when: on_fail` for the fail notification in the parallel portion?

**Comment by rob4629** [comment]
I agree. Having a way to notify at the end of the job would be ideal, as right now it can lead to a lot of confusion when multiple builds are triggered around the same time.

**Comment by KyleTryon** [comment]
Currently considering the idea of adding a job to the workflow which watches the API (from a small resource class container) waiting for the other jobs within the same workflow to complete.

This was done to create the SumoLogic orb: https://github.com/CircleCI-Public/sumologic-orb/

**Comment by rob4629** [comment]
Is it possible to call the slack orb jobs from within the [deploy step](https://circleci.com/docs/2.0/configuration-reference/#deploy) of a workflow? That way we don't need any additional logic for waiting on all containers completing

**Comment by KyleTryon** [comment]
@rob4629 Yes, but the gotchya is that the deploy step will never run if a job fails prior to that. The concept of a "post-job" that would run at the end of a workflow would help greatly with this. The currently workaround I am considering is to leave a job open during the entire time of the workflow which can spy on those other jobs.

**Comment by rob4629** [comment]
Hey @KyleTryon, are you able to give me an update on where you are with this? I wasn't able to give it much thought over the last few months, but it would be good to get something implemented as our current process isn't ideal.

**Comment by KyleTryon** [comment]
Hello @rob4629 Due to the issues described above there is no known perfect solution to this issue as it stands currently. There is talk internally of a potentially new feature to CircleCI which we may be able to utilize to remedy this type of issue but it may be some time before this feature is implemented so we may take advantage of it.

We could still update the default behavior of a notification to use the deploy command if we like. There would be some pros and cons of that, obviously you would get fewer notifications but the notification you get on a single node is not valuable, as you need the final results from all nodes.

I had believed we already had a public suggestion for the new feature I was mentioned above but I was not able to find it so I created a new one for us here: https://ideas.circleci.com/ideas/CCI-I-1300

I would like to ask anyone who is in this thread and interested in the progress of this feature to take a look and vote for the "idea" at the link above. The dev team counts votes when deciding what new features to implement next.

**Comment by rob4629** [comment]
Hi @KyleTryon, I wonder if this [Suggestion](https://ideas.circleci.com/ideas/CCI-I-344) is better suited?

It seems to have quite a bit of support, but so far no response.

**Comment by zachdavid** [comment]
Was able to work around this problem for years by using the built in support for slack messages through the old UI.  The integration would send one slack message at the end of the workflow with a count of how many jobs passed/failed. 
 
Quite disappointed that Circle CI is simply removing this functionality with no alternative workarounds when the old UI is deprecated 8/14/2020

There is currently no way to "wait" for other jobs that could potentially fail.  Just because one of the jobs of the workflow exited 1, does not necessarily mean the whole workflow run is a failure.  Is this not a fairly common use case @KyleTryon ?

**Comment by KyleTryon** [comment]
@zachdavid You are absolutely not wrong. When CircleCI released CircleCI 2.0 and workflows, a notification system was not released at that time. The back-end reasoning is related to asynchronous stuff that is currently being addressed. We hope to offer webhooks in the semi-near future, which could lead to us building a true Slack Bot which is the ultimate goal.

The Slack integration you are referring to has actually been officially unsupported since the launch of 2.0, the service was just not disabled. In the absence of that official webhook we attempted to provide a viable solution with orbs in the meantime.

We certainly agree that orbs do not offer an optimal experience for this type of integration now, though we were less sure when we originally created it. It is a common use case and one that needs to be addressed, ideally with a true integration rather than reusable configuration.

We have been championing and working on webhooks for workflows in the meantime and we hope to speak more on that soon 🎉 .

**Comment by zachdavid** [comment]
@KyleTryon I appreciate the response and the championing for your customers.

Outside of the slack integration - quite shocking to me that there is no "after" block in workflows that waits for all other jobs to execute regardless of pass/fail status.  "Requires" in the workflows stanza will never run if any of previous the jobs fails :(

**Comment by hsks** [comment]
Hi,
Any updates or suggestions on this? While everything works perfectly fine I would love to have a workflow completion hook where one could notify on workflow completion. Configuring an end job to notify about workflow completion will definitely work, but I am quite hesitant to add an extra job considering how spawning containers/environment in the job can add to the build time.

**Comment by atombender** [comment]
I'm also looking for a solution to this, as we are in the process of evaluating CircleCI. Like the other commenters, I find it somewhat unbelievable that a dependency graph system would not have a way to express nodes that should execute even if its "fan in" inputs fail. Status is just another piece of data input/output, surely, and shouldn't have to impact scheduling. Emitting a _single_ notification at the end of a run is pretty core to CI, isn't it? I've used a range of CI systems (from Drone to GitHub Actions to Semaphore to Travis), and this is supported out of the box by all of them.

**Comment by egallup02360** [comment]
Any updates on this? It's really painful for our team to get spammed with X messages after every test run.

**Comment by KyleTryon** [comment]
> Any updates on this? It's really painful for our team to get spammed with X messages after every test run.

Please see the first item in the Frequently Asked Questions:
https://github.com/CircleCI-Public/slack-orb/wiki/FAQ#slack-orb-faq

**Comment by jfirebaugh** [comment]
This is a serious shortcoming of the orb-based approach to notifications. Notifications should really be a first-class feature of the CI platform, so that true job and workflow-level notifications are possible.

**Comment by egallup02360** [comment]
@jfirebaugh We ended up getting around this issue by completely skipping the use of this orb and using the new webhooks feature of circleci. 

You can use a service like zapier to capture the payload and forward it along to slack. We opted to use our own custom endpoint though cause zapier can get expensive if used a lot.

Some useful keys from the payload:
```
Workflow Status: data[:workflow][:status]
Subject/Commit Message: data[:pipeline][:vcs][:commit][:subject]
Commit: data[:pipeline][:vcs][:revision]
Branch: data[:pipeline][:vcs][:branch]
URL to Workflow Run: data[:workflow][:url]
```
