### ISSUE TITLE
[Request] notify-on-recovery

### ISSUE THREAD

**Issue by LukeAskew** [CircleCI-Public/slack-orb#92]
It would be helpful to be notified when a job has a recovered from a failed state.

Currently, if you are setup to only `notify-on-failure` you have to manually hunt through jobs to verify that subsequent builds have succeed. This is particularly painful for orgs with many jobs.

I would love to take a crack at this, but I'm not sure its possible to get the previous job's status. Is this possible?

**Comment by KyleTryon** [comment]
Hello @LukeAskew this may be possible but it would mean in order to use the feature a user would also need a CircleCI API token available. I don't think that's too bad given it would be optional. The command could use the API to look at the previous jobs ran for that repository, in that branch (though I am realizing now this will be much harder for tagged commits). The API could show the job names and statuses of previous runs, which could be filtered down by branch. So I think it would be possible. 

https://circleci.com/docs/api/#recent-builds-for-a-single-project

**Comment by imnotjames** [comment]
@LukeAskew would #54 help?  Perhaps that flag mixed with a `success_only` flag?

**Comment by LukeAskew** [comment]
Sounds exactly right. Closing in favor of #54.

**Comment by imnotjames** [comment]
I'll open up a PR to add a `sucess_only` flag :)
